apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-apple-rn-cert-path
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
   apple-rn-push-cert.pem: {{ .Values.applePushSettings.apple_rn.privateCert | quote }}
