apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-apple-rnbeta-cert-path
  labels:
    chart: {{ include "mattermost-push-proxy.chart" . }}
    app: {{ include "mattermost-push-proxy.fullname" . }}
data:
   apple-rnbeta-push-cert.pem: {{ .Values.applePushSettings.apple_rnbeta.privateCert | quote }}
