{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "mattermost-push-proxy.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $ingressApiIsStable := eq (include "mattermost-push-proxy.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "mattermost-push-proxy.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "mattermost-push-proxy.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost-push-proxy.chart" . }}
{{- with .Values.ingress.labels }}
{{- toYaml . | nindent 4 }}
{{- end }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ .path }}
          {{- if $ingressSupportsPathType }}
          pathType: {{ default "ImplementationSpecific" .pathType }}
          {{- end }}
          backend:
            {{- if .customService }}
            {{- toYaml .customServiceSpec | nindent 12 }}
            {{- else if $ingressApiIsStable }}
            service:
              name: {{ $serviceName }}
              port:
                number: {{ $servicePort }}
            {{- else }}
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
            {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
