# Conditionally create the Apple certs secret if externalSecrets are not enabled
{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-apple-certs
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
  apple_auth_key: {{ .Values.applePushSettings.authKey | default "" | b64enc | quote }}
  apple_cert: {{ .Values.applePushSettings.apple.privateCert | default "" | b64enc | quote }}
  apple_rn_cert: {{ .Values.applePushSettings.apple_rn.privateCert | default "" | b64enc | quote }}
  apple_rnbeta_cert: {{ .Values.applePushSettings.apple_rnbeta.privateCert | default "" | b64enc | quote }}
---
{{- end }}

# Conditionally create the Android service files secret if externalSecrets are not enabled
{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-android-service-files
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
  android_serviceFile: {{ .Values.androidPushSettings.android.serviceFile | default "" | toJson | b64enc | quote }}
  android_rn_serviceFile: {{ .Values.androidPushSettings.android_rn.serviceFile | default "" | toJson | b64enc | quote }}
{{- end }}
