apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-apple-certs
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
  apple: {{ default "" .Values.applePushSettings.apple.privateCert | b64enc | quote }}
  apple_rn: {{ default "" .Values.applePushSettings.apple_rn.privateCert | b64enc | quote }}
  apple_rnbeta: {{ default "" .Values.applePushSettings.apple_rnbeta.privateCert | b64enc | quote }}
  