apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-apple-certs
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
  apple_auth_key: {{ default "" .Values.applePushSettings.authKey | b64enc | quote }}
  apple_cert: {{ default "" .Values.applePushSettings.apple.privateCert | b64enc | quote }}
  apple_rn_cert: {{ default "" .Values.applePushSettings.apple_rn.privateCert | b64enc | quote }}
  apple_rnbeta_cert: {{ default "" .Values.applePushSettings.apple_rnbeta.privateCert | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-android-service-files
  labels:
    app.kubernetes.io/name: {{ include "mattermost-push-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-push-proxy.chart" . }}
data:
  android_serviceFile: {{ default "" .Values.androidPushSettings.android.serviceFile | toJson | b64enc | quote }}
  android_rn_serviceFile: {{ default "" .Values.androidPushSettings.android_rn.serviceFile | toJson | b64enc | quote }}
