{{- if .Values.global.features.jobserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mattermost-enterprise-edition.jobserver.fullname" . }}
  labels:
    app: {{ template "mattermost-enterprise-edition.jobserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    component: "{{ .Values.global.features.jobserver.name }}"
spec:
  type: {{ .Values.global.features.jobserver.service.type }}
  clusterIP: None
{{- end -}}
