apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" .}}-discovery
  labels:
    component: {{template "fullname" .}}
    role: master
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    component: {{template "fullname" .}}
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
