apiVersion: v1
description: Mattermost Enterprise server with high availitibity.
name: mattermost-helm
version: 0.6.0
appVersion: 5.4.0
keywords:
- mattermost
- communication
- messaging
- team colaboration
home: https://mattermost.com
icon: http://www.mattermost.org/wp-content/uploads/2016/04/icon.png
source:
- https://github.com/mattermost/mattermost-server
- https://github.com/mattermost/mattermost-kubernetes
