apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.metricsPort }}"
        prometheus.io/path: "/metrics"
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-elasticsearch",
            "image": "appropriate/curl:latest",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sh", "-c", "until ! {{ .Values.global.features.elasticsearch }} || curl --max-time 5 http://{{ .Release.Name }}-mattermost-elasticsearch:9200 ; do echo waiting for elasticsearch; sleep 5; done;"]
          }
        ]'
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: api
        - containerPort: {{ .Values.service.metricsPort }}
          name: metrics
        - containerPort: {{ .Values.service.clusterPort }}
          name: cluster
        - containerPort: {{ .Values.service.gossipPort }}
          name: gossip
        livenessProbe:
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v3/general/ping
            port: {{ .Values.service.internalPort }}
        volumeMounts:
        - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json
        - mountPath: /mattermost/mattermost.mattermost-license
          name: mattermost-license
          subPath: mattermost.mattermost-license
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
        - name: config-json
          configMap:
            name: {{template "fullname" .}}-config-json
            items:
            - key: config.json
              path: config.json
        - name: mattermost-license
          configMap:
            name: {{template "fullname" .}}-mattermost-license
            items:
            - key: mattermost.mattermost-license
              path: mattermost.mattermost-license
