apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-mysqlmm-cnf
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  mysqlmm.cnf: |
{{include "mysqlmm.cnf" . | printf "%s" | indent 4}}
