apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
              {
                  "name": "remove-lost-found",
                  "image": "busybox:1.25.0",
                  "command": ["rm", "-fr", "/var/lib/mysql/lost+found"],
                  "volumeMounts": [
                      {
                          "name": "data",
                          "mountPath": "/var/lib/mysql"
                      }
                  ],
                  "imagePullPolicy": {{ .Values.imagePullPolicy | quote }}
              }
          ]'
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        {{- if .Values.mysqlAllowEmptyPassword }}
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        {{- else }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql-password
        {{- end }}
        - name: MYSQL_USER
          value: {{ default "" .Values.global.dbUser | quote }}
        - name: MYSQL_DATABASE
          value: {{ default "" .Values.global.dbName | quote }}
        ports:
        - name: mysql
          containerPort: 3306
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 20
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: mysqlmmconfig
          mountPath: /etc/mysql/conf.d/mysqlmm.cnf
      volumes:
      - name: mysqlmmconfig
        configMap:
          name: {{template "fullname" .}}-mysqlmm-cnf
          items:
          - key: mysqlmm.cnf
            path: mysqlmm.cnf
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
