{{- if and .Values.mattermostOperator.enabled .Values.mattermostOperator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "mattermost-operator.name" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "mattermost-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mattermost-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "mattermost-operator.name" . }}
  namespace: {{ template "mattermost-operator.namespace" . }}
{{- end }}
