{{- if and .Values.mattermostOperator.enabled .Values.mattermostOperator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "mattermost-operator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mattermost-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "mattermost-operator.name" . }}
  namespace: {{ template "mattermost-operator.namespace" . }}
{{- end }}
