{{- if and .Values.mattermostOperator.enabled .Values.mattermostOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mattermost-operator.name" . }}
{{- end }}
