apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-chaos-engine.fullname" . }}
type: Opaque
data:
  {{- toYaml .Values.containers.secrets.data | nindent 2 }}
stringData:
  {{- toYaml .Values.containers.secrets.stringData | nindent 2 }}
