apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-push-config-json
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  push-config.json: |
{{include "push-config.json" . | printf "%s" | indent 4}}

