dependencies:
  - name: mattermost-app
    version: 0.1.0
    tags:
      - core
  - name: mattermost-grafana
    version: 0.3.6
    tags:
      - metrics
      - loadtest
  - name: mattermost-loadtest
    version: 0.1.0
    tags:
      - loadtest
  - name: mattermost-prometheus
    version: 3.1.0
    tags:
      - metrics
      - loadtest
  - name: mattermost-proxy
    version: 0.1.0
    tags:
      - core
  - name: mysqlha
    version: 0.1.0
    tags:
      - core
    import-values:
      - child: "mysqlha"
        parent: global.dbconfig
  - name: mattermost-minio
    version: 0.1.3
    tags:
      - core