dependencies:
  - name: mysqlha
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    version: 0.4.0
    condition: global.features.database.useInternal
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.8.0
    condition: minio.enabled
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 7.1.0
    condition: global.features.grafana.enabled
