dependencies:
  - name: mysqlha
    version: 0.1.0
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    tags:
      - core
    import-values:
      - child: "mysqlha"
        parent: global.dbconfig