dependencies:
  - name: mattermost-app
    version: 0.1.0
    repository: "file://subcharts/mattermost-app"
    tags:
      - core
  - name: mattermost-db
    version: 0.2.6
    repository: "file://subcharts/mattermost-db"
    tags:
      - core
  - name: mattermost-grafana
    version: 0.3.6
    repository: "file://subcharts/mattermost-grafana"
    tags:
      - metrics
      - loadtest
  - name: mattermost-loadtest
    version: 0.1.0
    repository: "file://subcharts/mattermost-loadtest"
    tags:
      - loadtest
  - name: mattermost-prometheus
    version: 3.1.0
    repository: "file://subcharts/mattermost-prometheus"
    tags:
      - metrics
      - loadtest
  - name: mattermost-proxy
    version: 0.1.0
    repository: "file://subcharts/mattermost-proxy"
    tags:
      - core
  - name: minio
    version: 1.1.1
    repository: "@stable"
    tags:
      - core
