dependencies:
  - name: mysqlha
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    version: 0.3.0
    condition: global.features.database.useInternal
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.3.4
    condition: global.features.storage.enabled
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 6.7.4
    condition: global.features.grafana.enabled
