dependencies:
  - name: kube-lego
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.4.0
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.17.1
  - name: mysqlha
    repository: https://releases.mattermost.com/helm/mysqlha
    version: 0.2.2
    condition: mysqlha.enabled
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.3.0
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 6.7.0
