dependencies:
  - name: kube-lego
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.4.2
    tags:
      - ingress
  - name: nginx-ingress
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 0.20.3
    tags:
      - ingress
  - name: mysqlha
    repository: https://releases.mattermost.com/helm/mysqlha
    version: 0.2.2
    tags:
      - database
    condition: mysqlha.enabled
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 1.3.4
    tags:
      - storage
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 6.7.4
    tags:
      - metrics
