mysql:
  enabled: true
  mysqlRootPassword: "rootpassword"
  mysqlUser: "mmuser"
  mysqlPassword: "mmpassword"
  mysqlDatabase: mattermost

extraEnvVars:
  - name: TEST_SAMPLE
    value: honk

extraInitContainers:
  - name: test-init
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - "-c"
      - |
        echo "honk the planet"
        exit 0
