apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-nginx-conf
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  nginx.conf: |
{{include "mattermost-nginx.conf" . | printf "%s" | indent 4}}