apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-default-conf
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  default.conf: |
{{include "default.conf" . | printf "%s" | indent 4}}