apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-loadtestconfig-json
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  loadtestconfig.json: |
{{include "loadtestconfig.json" . | printf "%s" | indent 4}}
