apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "fullname" .}}-config-json
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
data:
  config.json: |
{{include "config.json" . | printf "%s" | indent 4}}
