apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: "Never"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /mattermost/config/config.json
            name: config-json
            subPath: config.json
          - mountPath: /mattermost/mattermost.mattermost-license
            name: mattermost-license
            subPath: mattermost.mattermost-license
          - mountPath: /mattermost-load-test/loadtestconfig.json
            name: loadtestconfig-json
            subPath: loadtestconfig.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config-json
          configMap:
            name: {{template "fullname" .}}-config-json
            items:
            - key: config.json
              path: config.json
        - name: mattermost-license
          configMap:
            name: {{template "fullname" .}}-mattermost-license
            items:
            - key: mattermost.mattermost-license
              path: mattermost.mattermost-license
        - name: loadtestconfig-json
          configMap:
            name: {{template "fullname" .}}-loadtestconfig-json
            items:
            - key: loadtestconfig.json
              path: loadtestconfig.json
