apiVersion: v1
kind: Secret
metadata:
  name: {{template "fullname" .}}-mattermost-license
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  mattermost.mattermost-license: {{ .Values.global.mattermostLicense | b64enc | quote  }}
