{{- if and .Values.mysqlOperator.enabled .Values.mysqlOperator.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "mysql-operator.name" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "mysql-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "mysql-operator.name" . }}
    release: {{ template "mysql-operator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "mysql-operator.name" . }}
subjects:
  - name: {{ template "mysql-operator.name" . }}
    namespace: {{ template "mysql-operator.namespace" . }}
    kind: ServiceAccount
{{- end }}
