{{- if and .Values.mysqlOperator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql-operator.name" . }}-orc
  namespace: {{ template "mysql-operator.namespace" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    release: {{ template "mysql-operator.name" . }}
data:
  TOPOLOGY_USER: {{ .Values.mysqlOperator.topology.user }}
  TOPOLOGY_PASSWORD: {{ .Values.mysqlOperator.topology.password }}
{{- end }}
