{{- if and .Values.mysqlOperator.enabled .Values.mysqlOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mysql-operator.name" . }}
  namespace: {{ template "mysql-operator.namespace" . }}
  labels:
    app: {{ template "mysql-operator.name" . }}
    release: {{ template "mysql-operator.name" . }}
{{- end }}
