{{- if and .Values.mysqlOperator.enabled .Values.mysqlOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mysql-operator.name" . }}
  namespace: {{ template "mysql-operator.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "mysql-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ template "mysql-operator.name" . }}
    release: {{ template "mysql-operator.name" . }}
{{- end }}
