{{- if and .Values.server.ingress.enabled .Values.global.features.grafana.enabled }}
{{- $releaseName := .Release.Name -}}
{{- $servicePort := .Values.server.httpPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}
spec:
  rules:
  {{- range .Values.server.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
            backend:
              service:
                name: {{ printf "%s-%s" $releaseName "grafana" | trunc 63 }}
                port:
                  number: {{ $servicePort }}
            pathType: ImplementationSpecific
            {{- else }}
            backend:
              serviceName: {{ printf "%s-%s" $releaseName "grafana" | trunc 63 }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end }}
