apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mattermost-enterprise-edition.fullname" . }}-init-config-json
  labels:
    app.kubernetes.io/name: {{ include "mattermost-enterprise-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost-enterprise-edition.chart" . }}
data:
  config.json: |
{{ include "config.tpl" . | printf "%s" | indent 4 }}
