{{- if .Values.mattermostApp.ingress.enabled -}}
{{- $serviceName := include "mattermost-enterprise-edition.fullname" . -}}
{{- $servicePort := .Values.mattermostApp.service.externalPort -}}
apiVersion: {{ include "mattermost-enterprise-edition.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "mattermost-enterprise-edition.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost-enterprise-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost-enterprise-edition.chart" . }}
  annotations:
    {{- if .Values.mattermostApp.ingress.annotations }}
{{ toYaml .Values.mattermostApp.ingress.annotations | indent 4 }}
    {{- end }}
    {{- if .Values.mattermostApp.ingress.tls }}
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  rules:
  {{- range $host := .Values.mattermostApp.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }}
  {{- end -}}
  {{- if .Values.mattermostApp.ingress.tls }}
  tls:
{{ toYaml .Values.mattermostApp.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
