{{- if or (and .Values.volumeConfig.usePVC .Values.volumeConfig.useEFS)
            (and .Values.volumeConfig.usePVC .Values.volumeConfig.useNFS)
            (and .Values.volumeConfig.useEFS .Values.volumeConfig.useNFS) }}
{{- fail "Only one of usePVC, useEFS, or useNFS can be enabled at a time." }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mattermost-calls-offloader.fullname" . }}
  labels:
    {{- include "mattermost-calls-offloader.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mattermost-calls-offloader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mattermost-calls-offloader.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mattermost-calls-offloader.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: offloader
              containerPort: 4545
              protocol: TCP
          env:
            {{- toYaml .Values.config | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /version
              port: offloader
          readinessProbe:
            httpGet:
              path: /version
              port: offloader
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
