apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mattermost-calls-offloader.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mattermost-calls-offloader.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mattermost-calls-offloader.serviceAccountName" . }}
