apiVersion: v1
kind: Service
metadata:
  name: {{ include "mattermost-calls-offloader.fullname" . }}
  labels:
    {{- include "mattermost-calls-offloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: offloader
  selector:
    {{- include "mattermost-calls-offloader.selectorLabels" . | nindent 4 }}
