{{- if .Values.global.features.loadTest.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "mattermost-enterprise-edition.fullname" .}}-loadtestconfig-json
  labels:
    app.kubernetes.io/name: {{ template "mattermost-enterprise-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ template "mattermost-enterprise-edition.chart" . }}
data:
  loadtestconfig.json: |
{{include "loadtestconfig.tpl" . | printf "%s" | indent 4}}
{{- end }}
