{{- if .Values.global.features.loadTest.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{template "mattermost-enterprise-edition.fullname" .}}-loadtestconfig-json
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{template "mattermost-enterprise-edition.name" .}}
data:
  loadtestconfig.json: |
{{include "loadtestconfig.tpl" . | printf "%s" | indent 4}}
{{- end }}
