{{- if .Values.global.features.loadTest.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{template "mattermost-enterprise-edition.fullname" .}}-loadtest
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.global.features.loadTest.replicaCount }}
  template:
    metadata:
      labels:
        app: {{template "mattermost-enterprise-edition.name" .}}-loadtest
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{template "mattermost-enterprise-edition.fullname" .}}-loadtest
          image: "{{ .Values.global.features.loadTest.image.repository }}:{{ .Values.global.features.loadTest.image.tag }}"
          imagePullPolicy: {{ .Values.global.features.loadTest.image.pullPolicy }}
          volumeMounts:
          - mountPath: /mattermost/config/config.json
            name: config-json
            subPath: config.json
          - mountPath: /mattermost/mattermost.mattermost-license
            name: mattermost-license
            subPath: mattermost.mattermost-license
          - mountPath: /mattermost-load-test/loadtestconfig.json
            name: loadtestconfig-json
            subPath: loadtestconfig.json
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: config-json
          configMap:
            name: {{template "mattermost-enterprise-edition.fullname" .}}-config-json
            items:
            - key: config.json
              path: config.json
        - name: mattermost-license
          secret:
            secretName: {{ template "mattermost-enterprise-edition.fullname" . }}-mattermost-license
        - name: loadtestconfig-json
          configMap:
            name: {{ template "mattermost-enterprise-edition.fullname" . }}-loadtestconfig-json
            items:
            - key: loadtestconfig.json
              path: loadtestconfig.json
{{- end }}
