apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mattermost-enterprise-edition.fullname" . }}
  labels:
    app: {{ template "mattermost-enterprise-edition.name" . }}
    chart: {{ template "mattermost-enterprise-edition.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mattermostApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mattermost-enterprise-edition.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "mattermost-enterprise-edition.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.mattermostApp.service.metricsPort }}"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        - name: "init-elasticsearch"
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c", "until ! {{ .Values.global.features.elasticsearch.enabled }} || curl --max-time 5 http://{{ .Release.Name }}-mattermost-elasticsearch:9200 ; do echo waiting for elasticsearch; sleep 5; done; echo init-elasticsearch finished"]
        - name: "init-mysql"
          image: "appropriate/curl:latest"
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c", "until ! {{ .Values.global.features.database.useInternal }} || curl --max-time 5 http://{{ .Release.Name }}-mysqlha-readonly:3306; do echo waiting for {{ .Release.Name }}-mysqlha; sleep 5; done;"]
      containers:
      - name: {{ template "mattermost-enterprise-edition.name" . }}
        image: "{{ .Values.mattermostApp.image.repository }}:{{ .Values.mattermostApp.image.tag }}"
        imagePullPolicy: {{ .Values.mattermostApp.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mattermostApp.service.internalPort }}
          name: api
        - containerPort: {{ .Values.mattermostApp.service.metricsPort }}
          name: metrics
        - containerPort: {{ .Values.mattermostApp.service.clusterPort }}
          name: cluster
        - containerPort: {{ .Values.mattermostApp.service.gossipPort }}
          name: gossip
        livenessProbe:
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: {{ .Values.mattermostApp.service.internalPort }}
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 15
          httpGet:
            path: /api/v4/system/ping
            port: {{ .Values.mattermostApp.service.internalPort }}
        volumeMounts:
        - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json
        - mountPath: /mattermost/mattermost.mattermost-license
          name: mattermost-license
          subPath: mattermost.mattermost-license
        resources:
{{ toYaml .Values.mattermostApp.resources | indent 10 }}
      volumes:
        - name: config-json
          configMap:
            name: {{template "mattermost-enterprise-edition.fullname" .}}-config-json
            items:
            - key: config.json
              path: config.json
        - name: mattermost-license
          secret:
            secretName: {{template "mattermost-enterprise-edition.fullname" .}}-mattermost-license
