apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mattermost-enterprise-edition.fullname" . }}-mattermost-license
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "mattermost-enterprise-edition.name" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  mattermost.mattermost-license: {{ .Values.global.mattermostLicense | b64enc | quote  }}
