apiVersion: v1
kind: Service
metadata:
  name: {{ include "mattermost-enterprise-edition.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mattermost-enterprise-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart:  {{ include "mattermost-enterprise-edition.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mattermost-enterprise-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: server
  type: {{ .Values.mattermostApp.service.type }}
  ports:
  - port: {{ .Values.mattermostApp.service.externalPort }}
    targetPort: {{ .Values.mattermostApp.service.internalPort }}
    protocol: TCP
    name: {{ .Values.mattermostApp.service.name }}
  - port: {{ .Values.mattermostApp.service.metricsPort }}
    targetPort: {{ .Values.mattermostApp.service.metricsPort }}
    protocol: TCP
    name: {{ .Values.mattermostApp.service.metricsName }}
