apiVersion: v1
kind: Service
metadata:
  name: {{ template "mattermost-enterprise-edition.fullname" . }}
  labels:
    app: {{ template "mattermost-enterprise-edition.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: {{ template "mattermost-enterprise-edition.name" . }}
  type: {{ .Values.mattermostApp.service.type }}
  ports:
  - port: {{ .Values.mattermostApp.service.externalPort }}
    targetPort: {{ .Values.mattermostApp.service.internalPort }}
    protocol: TCP
    name: {{ .Values.mattermostApp.service.name }}
  - port: {{ .Values.mattermostApp.service.metricsPort }}
    targetPort: {{ .Values.mattermostApp.service.metricsPort }}
    protocol: TCP
    name: {{ .Values.mattermostApp.service.metricsName }}
