apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
