{{- if and .Values.minioOperator.enabled .Values.minioOperator.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "minio-operator.name" . }}-binding
  namespace: {{ template "minio-operator.namespace" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "minio-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.minioOperator.appName }}-operator-role
subjects:
- kind: ServiceAccount
  name: {{ template "minio-operator.name" . }}-sa
  namespace: {{ template "minio-operator.namespace" . }}
{{- end }}
