{{- if and .Values.minioOperator.enabled .Values.minioOperator.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "minio-operator.name" . }}-binding
  namespace: {{ template "minio-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.minioOperator.appName }}-operator-role
subjects:
- kind: ServiceAccount
  name: {{ template "minio-operator.name" . }}-sa
  namespace: {{ template "minio-operator.namespace" . }}
{{- end }}
