{{- if and .Values.minioOperator.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "minio-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ template "minio-operator.namespace" . }}
  name: {{ template "minio-operator.namespace" . }}
  annotations:
    "helm.sh/hook-delete-policy" : post-delete
    "helm.sh/hook-weight": "-10"    
spec:
  finalizers:
  - kubernetes
{{- end }}
