{{- if and .Values.minioOperator.enabled .Values.minioOperator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "minio-operator.name" . }}-sa
  namespace: {{ template "minio-operator.namespace" . }}
{{- end }}
