name: "Validate PR"

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-22.04
    steps:
      # Checkout everything since ct uses git diff to determine charts
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0 
      - name: Execute Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs:
      - lint
    steps:
      # Checkout everything since ct uses git diff to determine charts
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0 
      - name: Execute Tests
        run: make test
