name: "Release"

on:
  push:
    branches:
      - master

concurrency: release

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    
    steps:
      # Checkout everything since ct uses git diff to determine charts
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0 
      - name: Release Charts
        run: make release
        env:
          CR_TOKEN: ${{ github.token }}
