name: "Release"

on:
  push:
    branches:
      - master

concurrency: release

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    
    steps:
      # Checkout everything since ct uses git diff to determine charts
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 #v4.3.0
        with:
          fetch-depth: 0 
      - name: Release Charts
        run: make release
        env:
          CR_TOKEN: ${{ github.token }}
