dependencies:
  - name: mysqlha
    repository: https://charts.helm.sh/incubator
    version: 2.0.0
    condition: global.features.database.useInternal
  - name: minio
    repository: https://charts.helm.sh/stable
    version: 5.0.26
    condition: minio.enabled
  - name: prometheus
    repository: https://charts.helm.sh/stable
    version: 11.4.0
    condition: global.features.grafana.enabled
