dependencies:
  - name: mysqlha
    repository: https://kubernetes-charts-incubator.storage.googleapis.com
    version: 2.0.0
    condition: global.features.database.useInternal
  - name: minio
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 5.0.26
    condition: minio.enabled
  - name: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 11.4.0
    condition: global.features.grafana.enabled
